# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Daintree's library
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
google_fonts: "Nanum+Gothic:400,700"
color_scheme: font

aux_links:
  "Daintree's GitHub":
    - "//github.com/daintree-henry"
aux_links_new_tab: true

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed


collections:
  tekton:
    permalink: "/:collection/:path/"
    output: true
  homekube:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    tekton:
      name: TEKTON
    homekube:
      name: K8S CONFIG FOR HOME